<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Yara</RootNamespace>
    <AssemblyName>yara</AssemblyName>
    <ApplicationIcon>yara.ico</ApplicationIcon>
    <DefaultItemExcludes>$(DefaultItemExcludes);yara-installer/**</DefaultItemExcludes>
    <Version>1.0.0</Version>
    <Product>yara</Product>
    <Description>Console audio visualizer for Windows</Description>
    <Copyright>Copyright (c) 2026 yara contributors</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
  </ItemGroup>

</Project>
