<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>yara-installer</AssemblyName>
    <ApplicationIcon>..\yara.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <Product>yara Installer</Product>
    <Description>Installer for yara, a console audio visualizer</Description>
    <Copyright>Copyright (c) 2026 yara contributors</Copyright>
    <NoWarn>CA1416</NoWarn>
    <RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\yara.ico" LogicalName="yara.ico" />
    <EmbeddedResource Include="embed\yara.exe.gz" LogicalName="yara.exe.gz" />
  </ItemGroup>

</Project>
